on:
    push:
        branches:
            - master

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      .yarn/cache
                  key: node_modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn lint
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      .yarn/cache
                  key: node_modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn test
